### ISSUE TITLE
[Feature suggestion] Axis names should support underscore (like `axis_name`)

### ISSUE THREAD

**Issue by Conchylicultor** [arogozhnikov/einops#100]
I got surprised that `einops` trigger an error for:

```python
x = np.ones((1, 2))
einops.rearrange(x, 'batch num_axis -> num_axis batch')
```
Which raises:
```
EinopsError:  Error while processing rearrange-reduction pattern "batch num_axis -> num_axis batch".
 Input tensor shape: (1, 2). Additional info: {}.
 Unknown character '_'
```

`einops` do not seems to support `_` in an axis name.
I think this behavior is quite surprising as `num_axis` is a very standard python variable name, so it would be natural to be accepted as axis name.

**Comment by Conchylicultor** [comment]
It seems to be fixed in recent version of einops

**Comment by arogozhnikov** [comment]
@Conchylicultor yes, it was changed a while ago. You've used some pretty old version
