### ISSUE TITLE
[Feature suggestion] Custom backend support

### ISSUE THREAD

**Issue by MilesCranmer** [arogozhnikov/einops#120]
Could the einop operations allow for an optional "backend" keyword argument? This would allow the user to write a class for an arbitrary framework that inherits from `einops.AbstractBackend` and redefines the required functions.

I was about to suggest a backend for Dask arrays (distributed operations on out-of-memory arrays - https://github.com/dask), but I realized it may prevent feature creep in the longterm if this package simply allows custom backends.

Cheers,
Miles

**Comment by machineko** [comment]
Its already implemented but hidden.
Check https://github.com/arogozhnikov/einops/blob/900f84420d5ccfe57d779be098fe0ae09f036873/einops/_backends.py#L55 i already modified few stuff there before its easy 😸

**Comment by MilesCranmer** [comment]
I saw that but assumed you would need to actually write a new backend in the source file. 

Wait, does https://github.com/arogozhnikov/einops/blob/900f84420d5ccfe57d779be098fe0ae09f036873/einops/_backends.py#L33 automatically find your backend if you implement it in a local file? If so, awesome. That's way cleaner!

**Comment by arogozhnikov** [comment]
> automatically find your backend if you implement it in a local file? 

correct! Just add more element to that collection (even from outside code) and it will be picked up.

So, something like this will work (should be called before using of course):

```python
def add_my_backend():
   from einops._backends import backends
   backends = [*bakends, MyDaskBackendClass]
```

**Comment by MilesCranmer** [comment]
That is amazing, thanks!!
