### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dvolgyes** [arogozhnikov/einops#127]
It's been almost a year since the last PyPi release,
and it's been a while since the last commit.
Any chance to make a new release? :)

**Comment by leondgarse** [comment]
Ya, currently pypi version `0.3.0` is broken for the latest `TF 2.6.0`:
```py
tf.__version__
# '2.6.0'
from einops import rearrange
print(rearrange(tf.ones([1, 224, 224, 3]), 'B H W C -> B C H W').shape)
# AttributeError: module 'keras.backend' has no attribute 'is_tensor'
```
This issue is already fixed in github latest version:
```sh
pip install git+https://github.com/arogozhnikov/einops.git
```
```py
from einops import rearrange
print(rearrange(tf.ones([1, 224, 224, 3]), 'B H W C -> B C H W').shape)
# (1, 3, 224, 224)
```
So any chance a new release?

**Comment by arogozhnikov** [comment]
Done, @leondgarse new version should be on pypi now.

**Comment by dvolgyes** [comment]
Hi,

Maybe you could also tag the release commit. :)

-------- Original Message --------

**Comment by arogozhnikov** [comment]
@dvolgyes yup, done
