### ISSUE TITLE
[Feature suggestion] std in reduce?

### ISSUE THREAD

**Issue by chris-tkinter** [arogozhnikov/einops#128]
Hi, I was calculating the per-channel mean and std of the video dataset so that I can normalize my input videos. Normally I would do something like this
```python
# number of videos = 74
# number of frames = 8
# image size = 224
# channel = RGB
videos = np.random.random((74, 8, 224, 224, 3))
videos = rearrange(videos, 'b f h w c -> (b f h w) c')
MEAN = videos.mean(0)
STD = videos.std(0)
```
But in fact for the MEAN, we can do it directly by
```python
MEAN = reduce(videos, 'b f h w c -> c', 'mean')
```
however we can't use `reduce` for calculating std. Therefore I am wondering if it's possible to support std operation on the `reduce`. This could be helpful.

Thanks!

**Comment by arogozhnikov** [comment]
surprised it's not there yet, let's implement

**Comment by arogozhnikov** [comment]
I've looked at it, and realized why this wasn't implemented: there is no agreement in what is std between frameworks. 

E.g. numpy doesn't make ndof correction, but pytorch does. Both options make sense, but einops shouldn't conflict with ops definitions in the frameworks
