### ISSUE TITLE
Torch `Rearrange` layer is unused in one of tests

### ISSUE THREAD

**Issue by StephenHogg** [arogozhnikov/einops#129]
**Describe the bug**
In the [tests for the torch Rearrange and Reduce layers](https://github.com/arogozhnikov/einops/blob/fdfb9da59dd9552f3d69e3bfe87b4f400fa2b383/tests/test_layers.py#L190), the Reduce layer is used twice but the Rearrange layer is not used at all and therefore not tested.

**Reproduction steps**
Run the relevant test

**Expected behavior**
The Rearrange layer should be used in the test for whether torch layers are working

**Your platform**
N/A

**Comment by arogozhnikov** [comment]
This is not a big deal, but thanks for flagging - I'll add Rearrange there.

**Comment by StephenHogg** [comment]
No worries - saw it in passing and thought it would be worth pointing out.
