### ISSUE TITLE
[BUG] rearrange not return expected array 

### ISSUE THREAD

**Issue by Psilym** [arogozhnikov/einops#155]
**Describe the bug**
When i use `einops.rearrage(x,'N1 C (k1 k2 N2) -> (N1 N2) C k1 k2')`, I did not obtain the expected array.
To fix the problem, I use `x = x.reshape(N1,C,N2,k,k).permute(0,2,1,3,4); x=x.reshape(N1*N2,C,k,k)` and successfully get the targeting results.

**Reproduction steps**
Init x as a random array with shape [N1, C, k1*k2*N2]. k1 and k2 can be both set as 3. N1, N2, C can be set as other numbers.

**Expected behavior**
code `einops.rearrage(x,'N1 C (k1 k2 N2) -> (N1 N2) C k1 k2')` can return `x.reshape(N1,C,N2,k,k).permute(0,2,1,3,4).reshape(N1*N2,C,k,k)`

**Your platform**
Version of einops = 0.3.2, python = 3.8 and DL package = torch 1.10.0

**Comment by arogozhnikov** [comment]
HI @Psilym,
two ways you described are not equivalent.

This

```
x = torch.arange(N1 * N2 * C * k * k)([N1, C, N2, k, k])
x.reshape(N1,C,N2,k,k).permute(0,2,1,3,4).reshape(N1*N2,C,k,k)
```

Is equivalent to 

```
einops.rearrage(x,'N1 C (N2 k1 k2) -> (N1 N2) C k1 k2')
```

but you provided it with a different pattern.

**Comment by Psilym** [comment]
Thanks for the quick response. It is my misunderstanding of the sequence problem. It seems that the sequence of x1 and x2 in '(x1 x2)' does matter.
