### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yunzqq** [arogozhnikov/einops#157]
I use tensorflow 1.13 show that  module 'tensorflow' has no attribute 'is_tensor'

**Comment by arogozhnikov** [comment]
Hi @yunzqq 
einops==0.1.0 and 0.2.0 should support TF1.x - try downgrading.

Tensorflow 2 was released ~2 years ago, there was a plenty of time for migration and there are many reasons to migrate. 
TF 0.x and TF 1.x will not be supported by any future release of einops.

**Comment by yunzqq** [comment]
Thank you very much
