### ISSUE TITLE
[BUG] parse_shape should reject template with repeated axes

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [arogozhnikov/einops#158]
**Describe the bug**
`parse_shape` accepts repeated axis name

**Reproduction steps**
```python
parse_shape(np.zeros((10, 20, 30)), 'b b c')
# returns {'b': 20, 'c': 30}
```

**Expected behavior**
All the other methods in einops raise an exception, so I expect an error with `parse_shape` as well.

**Your platform**
All the platforms

In general, I would expect that the behavior is consistent between all the functions in the package.

**Comment by arogozhnikov** [comment]
Thanks for pointing @dmitriy-serdyuk, I agree that behavior should be consistent
