### ISSUE TITLE
[Feature suggestion] Expand operation for PyTorch

### ISSUE THREAD

**Issue by qinzheng93** [arogozhnikov/einops#160]
Shall einops add `expand` operation as `torch.expand`? Although `expand` and `repeat` have similar functions, `expand` does not trigger memory copy and it significantly faster than `repeat`. Consider the following case, `torch.expand` is 10x faster than `torch.repeat`.

```python
a = torch.rand(1, 1000, 1000).cuda()
b = a.unsqueeze(1).expand(-1, 4, -1, -1)
c = einops.repeat(b, 'b n m -> b h n m', h=4)
```

For other backends like NumPy, `expand` can be a simple alias of `repeat`.

**Comment by arogozhnikov** [comment]
@qinzheng93 in the latest release repeat uses expand under the hood, and when possible view is returned, not copy
