### ISSUE TITLE
[Feature suggestion] add ellipsis to parse_shape

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [arogozhnikov/einops#161]
Proposal: allow ellipsis in `parse_shape`. For example `parse_shape(np.zeros((10, 20, 30, 40)), 'a ... b')` should return `dict(a=10, b=40)`

1. Use cases:
  - To simplify generic code, such as patterns that work for single example and batch, for an image and a video. A more concrete example
```python
def forward_prop(x):
  # x can be a batch [batch_size, time, features] or just single example [time, features]
  y = do_something(x) # combines all timesteps [batch_size, (time, channels)]
  rearrange(y, '... (t c) -> ... t c', **parse_shape(x, '... t _'))
```
or 
```python
def process_video_or_image(x):
  parse_shape(x, 'b ... w h c')
```
  - Tensors with lots of dims that do not matter. For example, a video which is split into tubelets as in ViViT has shape
     [batch, time, tubelet_z, tubelet_x, tubelet_y, width, height, channels]. It is just too cumbersome to write
```python
parse_shape(tubelet_tensor, '_ _ _ _ _ _ _ channels')
```
instead of 
```python
parse_shape(tubelet_tensor, '... channels')
```
2. **Implementation**. See #162 
3. **Integrity**. This addition plays well with other operations. Rearrange and repeat work with ellipsis.

**Comment by arogozhnikov** [comment]
ellipsis is easy to implement in define-by-run frameworks (imperative in einops terminology), but not so in symbolic (mxnet, tensorflow in symbolic regime, tracing and scripting in tf, jax, torch). 

Before integrating this functionality, make sure to build an additional test suite (more dimensions/less dimensions, with/without ellipsis).

**Comment by dmitriy-serdyuk** [comment]
At the moment I implemented ellipsis by substituting it with a required number of "_". For example, the pattern in  `parse_shape(np.zeros((2, 3, 4, 5)), 'b ... c')` becomes `'b _ _ c'`. As far as I understand this should work in all the cases where parse_shape works now.

I'll add the tests though.
