### ISSUE TITLE
[BUG] Deprecation warning for __floordiv__

### ISSUE THREAD

**Issue by bsun0802** [arogozhnikov/einops#163]
**Describe the bug**
A deprecation warning shown for `eniops==0.3.2` and `torch==1.10.1+cu113`

**Reproduction steps**
```
/home1/bos/.local/lib/python3.8/site-packages/einops/einops.py:179: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
```

**Expected behavior**
Maybe this can help you eliminate this warning and consider which div to use.

**Your platform**
`eniops==0.3.2` and `torch==1.10.1+cu113` and `python=3.8.8`

**Comment by arogozhnikov** [comment]
Thanks for reporting, @bsun0802 
Issue was already reported #130, this is up to pytorch team to fix, not einops.
