### ISSUE TITLE
[BUG] einops materializes tensors that could be views

### ISSUE THREAD

**Issue by martenlienen** [arogozhnikov/einops#167]
**Describe the bug**
That a lot for this great library! My code looks much nicer now. Today I noticed that einops exhibits suboptimal behavior when repeating tensors in ways that could be views. In the example below, expanding with PyTorch creates a view that actually reuses the same memory as the original tensor. If I use einops instead to expand the dimensions, I get a fully realized tensor with a much larger memory footprint.

**Reproduction steps**
```python
$ ipython
Python 3.9.9 (main, Jan  5 2022, 20:20:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.
Exception reporting mode: Verbose

In [1]: x = torch.arange(10)

In [2]: import einops as eo

In [3]: a = eo.repeat(x, "i -> 8 3 i")

In [4]: a.storage().size(), a.storage().data_ptr()
Out[4]: (240, 93944369638784)

In [5]: b = x.expand((8, 3, -1))

In [6]: b.storage().size(), b.storage().data_ptr()
Out[6]: (10, 93944370155264)

In [7]: x.storage().size(), x.storage().data_ptr()
Out[7]: (10, 93944370155264)
```

**Expected behavior**
I would expect einops to be as efficient as creating the view directly.

**Your platform**
```
torch==1.10.1
einops==0.3.2
```

**Comment by arogozhnikov** [comment]
Check einops==0.4.0. Your example

```python
import torch
x = torch.arange(10)
​
import einops as eo
​
a = eo.repeat(x, "i -> 8 3 i")
b = x.expand((8, 3, -1))
​
print(a.storage().size(), a.storage().data_ptr())
print(b.storage().size(), b.storage().data_ptr())
print(x.storage().size(), x.storage().data_ptr())
```

outputs
```
10 140468281362624
10 140468281362624
10 140468281362624
```

**Comment by martenlienen** [comment]
Thanks for the quick response! I did not consider the possibility that there might have been a new version released between when I installed einops two days ago and now.
