### ISSUE TITLE
where to import the resources used in tutorials?

### ISSUE THREAD

**Issue by MiladInk** [arogozhnikov/einops#169]
I was following the tutorials as they are in [here](http://einops.rocks/1-einops-basics/). I am wondering where are the resources and images used in this tutorial so maybe I can have the same result as shown in the tutorial? 

Thanks for the einops, it is great!

**Comment by arogozhnikov** [comment]
Hi @MiladInk, see this discussion thread https://github.com/arogozhnikov/einops/discussions/132
