### ISSUE TITLE
[BUG] Space-to-depth/Depth-to-space are not inverse to each other in Tut. 2.

### ISSUE THREAD

**Issue by LvanderGoten** [arogozhnikov/einops#170]
The second tutorial suggests that the given tensor transformations **space-to-depth** and **depth-to-space** are inverse to each other. The following reveals that this is not the case:
```
import numpy as np
from einops import rearrange

b, c, h, w = 10, 32, 100, 200
x = np.random.randn(b, c, h, w)

# space-to-depth
y = rearrange(x, 'b c (h h1) (w w1) -> b (h1 w1 c) h w', h1=2, w1=2)  

# depth-to-space
z1 = rearrange(y, 'b (c h1 w1) h w -> b c (h h1) (w w1)', h1=2, w1=2) 
print(np.linalg.norm(x - z1)) # NOT equal to 0.0
```
The error can be corrected by doing:
```
z2 = rearrange(y, 'b (h1 w1 c) h w -> b c (h h1) (w w1)', h1=2, w1=2) 
print(np.linalg.norm(x - z2))  # equals 0.0 now
```
It would be great if you could adapt the tutorial.

P.S: Another thing regarding the same topic. In the first tutorial (**Order of axes matters**) it is written:
```
# order of axes in composition is different
# rule is just as for digits in the number: leftmost digit is the most significant, 
# while neighboring numbers differ in the rightmost axis.
```
I think this explanation needs some polishing, it is not really clear what is meant.

**Comment by arogozhnikov** [comment]
Thanks for catching, pushed a fix.

I believe analogy with digits in a number is the simplest to grasp and to remember. 
If you have suggestion on better wording/preseting - welcome.

**Comment by LvanderGoten** [comment]
The problem is I don't really understand the analogy but I think it would be very interesting if you could phrase it in some other way.
