### ISSUE TITLE
[BUG] einops 0.4.0 requires numpy

### ISSUE THREAD

**Issue by lucidrains** [arogozhnikov/einops#175]
Hi Alex! Big fan of einops :) There seems to be a new issue with 0.4.0 when I upgraded to it today

Einops 0.4.0 has an import for numpy (https://github.com/arogozhnikov/einops/blob/master/einops/einops.py#L7) even though no dependencies listed in setup.py. This breaks a couple of repositories when the tests are run

Expected Behavior:
Should be able to install Einops without it throwing an error about lacking numpy

**Comment by arogozhnikov** [comment]
Hi, thanks for reporting. 

np is used in docstrings, so it is helpful for convenience, but surely I want to avoid import. 

Can you check what happens if np is imported like this:

```python
if typing.TYPE_CHECKING:
    import numpy as np
```

WiIl your tests fail in this case?

**Comment by lucidrains** [comment]
> Hi, thanks for reporting.
> 
> np is used in docstrings, so it is helpful for convenience, but surely I want to avoid import.
> 
> Can you check what happens if np is imported like this:
> 
> ```python
> if typing.TYPE_CHECKING:
>     import numpy as np
> ```
> 
> WiIl your tests fail in this case?

that fixes it!

**Comment by arogozhnikov** [comment]
kk, will patch tonight

**Comment by lucidrains** [comment]
@arogozhnikov can i treat you to dinner some time?
![Screenshot from 2022-03-03 14-34-10](https://user-images.githubusercontent.com/108653/156664240-b0ecfad8-1f58-470b-be23-59d947fa0c3f.png)
coast seems clear :)

**Comment by arogozhnikov** [comment]
thx, merged and bumped the version. 

Will reach out when I'm in SF (likely weekend)
