### ISSUE TITLE
[BUG] Einops creates pointers instead of cloning

### ISSUE THREAD

**Issue by hypnopump** [arogozhnikov/einops#178]
**Describe the bug**
Einops Repeat creates pointers to the same object in memory instead of cloning the object. 

**Reproduction steps**
It worked in V3.2
<img width="434" alt="Captura de pantalla 2022-03-17 a las 18 09 10" src="https://user-images.githubusercontent.com/16491423/158857970-8c863060-9fee-48eb-ba92-a4ffbe8c215c.png">
But 
<img width="317" alt="Captura de pantalla 2022-03-17 a las 18 08 39" src="https://user-images.githubusercontent.com/16491423/158858029-b6e34cd7-2c6e-4be3-ab4d-2e709c8fa1d4.png">
does not work in V4

**Comment by hypnopump** [comment]
this is the root of all evil @arogozhnikov https://github.com/arogozhnikov/einops/commit/2215145061f48949a8cb9084c991fa88a3220021#diff-0c99c4eda1d9767e3967a1e1fbae23b1df5eec81727bce9a90c4e57fdbea56e9R336
one could solve it by adding `x = x.contiguous()` after that expand method or by going back to `repeat`.

Thinking about speed/performance here:
<img width="568" alt="Captura de pantalla 2022-03-17 a las 18 28 21" src="https://user-images.githubusercontent.com/16491423/158859757-a4f2254b-a3a7-477a-b45f-5f51d0ac44bb.png">

Seems clear we should go for `.contiguous()`

**Comment by arogozhnikov** [comment]
Hi @hypnopump 
It is a feature, not a bug, see #160, #167.
It was introduced in 0.4.0, see release notes

**Comment by hypnopump** [comment]
riiigghht okay and do you consider adding the call to `contiguous` as an optional or prefer to keep it like this?

https://github.com/hypnopump/einops/commit/822e516f21e91592d265d10202934713e6d03ba5#diff-8c6f53c140e58ff70184d8bc9ed1d8cea74932809948d0a9885b086692b6a24bR58

this works, it would just need an argument passed for whether this should be called or not. 

Having this option would be ideal for me, and i would say it could widen the range of applicability. But i dont know if having that extra arg is too much trouble. 

Idk, ur package ur rules. Thx for the amazing work so far btw

**Comment by arogozhnikov** [comment]
Unfortunately, having an additional arg makes sense for pytorch, but not for other frameworks, because some of them do not have a concept of view and do not provide any control over layout. 

So adding an argument would create confusion and will be an unholdable promise for other frameworks. 

The right way would be having `.contiguous()` or `.clone()` in user code after call to repeat.

> Idk, ur package ur rules. Thx for the amazing work so far btw

Thank you for kind words!
