### ISSUE TITLE
A question about repeat

### ISSUE THREAD

**Issue by NonvolatileMemory** [arogozhnikov/einops#183]
Hi Alex,

Thanks for your great work! I have a question about the repeat/copy operator, like following:

output_tensor = repeat(input_tensor, 'h w -> h w c', c=3)

will the output_tensor just like torch.expand(), which only create a new view of the input_tensor or like torch.repeat() which just assign new memory ?

**Comment by arogozhnikov** [comment]
Hi Cunxiao,

specifically for torch backend behavior of repeat changed recently in einops 0.4.0 from repeat-like to expand-like.

When possible, einops should return view not copy for lower memory and compute. 


There are multiple cases when resulting tensor can't be a view, for instance:

```
'(h1 h2) ->  (h1 3 h2) '
```

in such cases einops produces a new tensor.

**Comment by NonvolatileMemory** [comment]
thx alex!
