### ISSUE TITLE
Could we rearrange only dims in tail?

### ISSUE THREAD

**Issue by IcarusWizard** [arogozhnikov/einops#186]
Hi, thanks for the great project! I am enjoying using it in all of my deep learning projects.

I am currently implement some function to deal with both single frame and sequence of frames, and I want to do some rearrange to the tensor. That is, sometime the input is in the shape of `t b (m c)` while some time it is in the shape of `b (m c)`, and I want to split the last dim with rearrange. From what I know, I can write two lines of code with if else to handle each case, i.e. `t b (m c) -> t b m c` and `b (m c) -> b m c`. I wonder if there is a better way to achieve that?

**Comment by arogozhnikov** [comment]
Hi @IcarusWizard 
`... b (m c) -> ... b m c` is what you want
