### ISSUE TITLE
[BUG] Error message "Ellipsis found in left side...", when it's on the right side, not the left

### ISSUE THREAD

**Issue by johannes-riecken** [arogozhnikov/einops#189]
**Describe the bug**
I'm a big fan of your library and in the process of writing a [Haskell version](https://github.com/johannes-riecken/einops-haskell/), which is still in the very early, messy stages, though I'd be happy about your input later. I noticed a small bug, which is that the error message talks about the left side, when it should be the right side.

**Reproduction steps**

``` python
import einops
import numpy as np

print(einops.rearrange(np.array([]), ' -> ...'))
# gives "einops.EinopsError: Ellipsis found in left side, but not right side of a pattern  -> ..."
```

**Expected behavior**
What you expected to happen.

An error message like:

> Ellipsis found in right side, but not left side of a pattern  -> ...

**Your platform**
Python 3.9.12
einops 0.4.1

**Comment by arogozhnikov** [comment]
thanks for the catch @johannes-riecken . Curious to see examples of how one can use einops in haskell
