### ISSUE TITLE
[BUG] cuBLAS not called in einops example operations

### ISSUE THREAD

**Issue by KUEE1080** [arogozhnikov/einops#190]
**Describe the bug**
When I run the einops example operations described in
https://github.com/arogozhnikov/einops/blob/master/docs/1-einops-basics.ipynb  ,
it seems that none of the operations call cuBLAS API. I wonder if any of these operations can be implemented with cuBLAS function calls, which are highly optimized. Or is it a bug? Thanks in advance.

**Reproduction steps**
Implemented einops operations described in the tutorial link. Used Pytorch.

**Expected behavior**
When profiled with nsight-system (nvidia gpu profiler), it does not call any cuBLAS functions.

**Your platform**
Version of einops, python and DL package that you used
Einops: 0.4.1
python: 3.9.12
pytorch: 1.11.0 (py3.9_cuda11.3_cudnn8.2.0_0 )

**Comment by arogozhnikov** [comment]
Hi, @KUEE1080 

> it seems that none of the operations call cuBLAS API. I wonder if any of these operations can be implemented with cuBLAS function calls, which are highly optimized. Or is it a bug? Thanks in advance.

That's not a bug, almost none of einops operations can be implemented via cuBLAS. 

Those few operations that benefit from BLAS systems (e.g. EinMix layer) rely on downstream framework (e.g. pytorch), and in most cases framework would use cuBLAS to optimize those (if tensors are on GPU). 
However notebook you tried to profile is 1) about numpy 2) does not use GPU 3) those ops can't be optimized by BLAS

**Comment by KUEE1080** [comment]
Thanks for the response. Helped me a lot! :)
