### ISSUE TITLE
[BUG][Different results of einops.repeat and torch.repeat]

### ISSUE THREAD

**Issue by zerzerzerz** [arogozhnikov/einops#202]
**Describe the bug**
I think maybe this is a bug of `repeat`

**Reproduction steps**
```python
a = torch.rand(2)
a1 = a.clone()
```
Assume I get `a = tensor([0.5437, 0.9714])`
If I use the `einops.repeat()` like
```python
b = repeat(a,'t -> n t',n=2)
b[0,0] += 1
```
, then I got
```python
b = tensor([[1.5437, 0.9714],
            [1.5437, 0.9714]])
```

**Expected behavior**
If I use the `repeat` of `pytorch`, it will be:
```python
b1 = a1.repeat(2,1)
b1[0,0] += 1
```
Then I got
```python
b1 = tensor([[1.5437, 0.9714],
             [0.5437, 0.9714]])
```
I want to know whether this is a feature or bug. I got different results under `einops.repeat` and `torch.repeat`.
If I want to modify `b[0,0]` without modifying `b[1,0]` under `einops.repeat`, what should I do? Thanks!

**Your platform**
einops==0.4.1
torch==1.12.0
Python==3.8.13

**Comment by arogozhnikov** [comment]
Hi,
repeat in pytorch has semantics of torch.expand following requests from community

see e.g. https://github.com/arogozhnikov/einops/issues/183 and https://github.com/arogozhnikov/einops/issues/178

If you need a materialized copy, use repeat(...).clone()

**Comment by zerzerzerz** [comment]
Thanks! And maybe it will be better to add an argument to control this function return a view or a new copy of data? Or highlight it works like `torch.expand` not `torch.repeat` although it names `einops.repeat`. In a word, einops is an elegant and I love. Thank you!
