### ISSUE TITLE
[BUG] mean reduction doesn't work with torch.bfloat16 tensors

### ISSUE THREAD

**Issue by calebthomas259** [arogozhnikov/einops#206]
Thanks for making einops, it's a really helpful package!

**Describe the bug**
When I try to use `reduce()` on a [`torch.bfloat16` tensor](https://pytorch.org/docs/stable/tensor_attributes.html#torch-dtype) , I get an error:

    NotImplementedError: reduce_mean is not available for non-floating tensors

As far as I can tell, there's a trivial fix (we could just add `torch.bfloat16` to the backend's [list of float types](https://github.com/arogozhnikov/einops/blob/38485ce7eeae9240c66cb4f77c6f615b323e1c37/einops/_backends.py#L356)). Although, I'm not sure if there are implications anywhere else in the codebase...

**Reproduction steps**
```
import torch
from einops import reduce

x = torch.arange(6).reshape(2, 3).to(torch.bfloat16)
reduce(x, "h w -> h", "mean") # raises error
```

**Your platform**
- Python:  3.10.6
- PyTorch: 1.12.1
- einops: 0.4.1

Cheers!

**Comment by anhnami** [comment]
Had the same issue

**Comment by arogozhnikov** [comment]
should be fixed now, updated version will be released on pypi soon
