### ISSUE TITLE
Time for a release?

### ISSUE THREAD

**Issue by jph00** [arogozhnikov/einops#208]
@arogozhnikov thanks so much for this great library. I'd love to use it in our upcoming course, including features you've added recently. However there hasn't been any releases for 6 months, so stuff like `einsum` is currently only available when installing from master.

Any chance you might be able to cut a release sometime soon-ish?

**Comment by arogozhnikov** [comment]
will do this week

**Comment by arogozhnikov** [comment]
done! `pip install einops==0.5.0`

**Comment by pyscorcher** [comment]
Awesome, would it also be possible to update the corresponding [conda package](https://anaconda.org/conda-forge/einops)? Conda is the recommended way to use pytorch so I guess many people (me included:) would appreciate that too! Thanks for all your work!

**Comment by arogozhnikov** [comment]
Hi @pyscorcher 
I don't manage conda package, so it's up to their maintainers.
Note aside, einops is pure-python package and conda's pip would work equally well
