### ISSUE TITLE
The library is not typed

### ISSUE THREAD

**Issue by RomainBrault** [arogozhnikov/einops#215]
**Describe the bug**

MR #211 add py.typed to enable type checking support. However the library is not fully typed (at least not the public interface, see for instance https://github.com/arogozhnikov/einops/blob/master/einops/layers/torch.py.

Now mypy is complaining on each einops.layers.torch class call (Reduce, Rearrange, etc.).

-> error: Call to untyped function "Rearrange" in typed context  [no-untyped-call]

The library should not have a `py.typed` file until its public interface is fully typed.

**Reproduction steps**
run mypy on any source file containing, for instance, from `einops.layers.torch import Rearrange`

**Expected behavior**
mypy should not raise [no-untyped-call] errors

**Your platform**
Ubuntu 22.04

**Comment by RomainBrault** [comment]
I can see two quick and dirty solutions:

- remove the py.typed
- type any untyped public functions with `Any`

**Comment by arogozhnikov** [comment]
for pytorch, is it only constructors that need to be annotated? 
does mypy demand to annotate `__call__` or some other functions? 

If it's only constructors, may worth just annotating that (potentially, with Any).

**Comment by RomainBrault** [comment]
@arogozhnikov Yes in  my case it seems that only the constructors are problematic (so far I tested Rearrange and Reduce in pytorch). The functional api does not seeems to raise (I only tried the rearrange function from pytorch).

**Comment by arogozhnikov** [comment]
@RomainBrault 
I've annotated the rest of public API in this branch: 
https://github.com/arogozhnikov/einops/tree/type-hinting 

Check if that branch works with your setup

**Comment by RomainBrault** [comment]
Thanks! I'll have time to test this next weekeend. But just looking at the code, it looks fine.
