### ISSUE TITLE
Allow line breaks in format string

### ISSUE THREAD

**Issue by forieux** [arogozhnikov/einops#220]
Actually, einops does not allow line breaks in the format string. However, it could improve readability. For instance, when we have a tensor with a lot of dimensions we can't write

```python
out = einsum(
    tensor1,
    tensor2,
    """a b c d e f g h,
           c d     g h
    -> a b     e f g h
    """,
)
```
because the line breaks are not recognized.

**Comment by arogozhnikov** [comment]
Hi @forieux 
too strange/narrow case, just add `.replace('\n', '')` in the end of multiline. Or make a wrapper function

**Comment by forieux** [comment]
OK, I see no problem. If I propose a patch, do you think you would accept it?

**Comment by arogozhnikov** [comment]
well, nope: einops is about matching on semantics of axes, not positions; I see no reason to encourage this kind of usage
