### ISSUE TITLE
problem with styles

### ISSUE THREAD

**Issue by oMalyugina** [arogozhnikov/einops#23]
The beginning of "Improving RNN language modelling"  and "CNNs for text classification" blocks aren't visible in https://arogozhnikov.github.io/einops/pytorch-examples.html

und typos:  "Improving RNN language modilling" - modelling. ^_^

**Comment by arogozhnikov** [comment]
Fixed it, could you please try afain?
https://arogozhnikov.github.io/einops/pytorch-examples.html

Thanks
