### ISSUE TITLE
instructions for contributing?

### ISSUE THREAD

**Issue by elenishor** [arogozhnikov/einops#230]
Are there instructions for how to set up the project for contributing? The link on the README is broken. I tried building the project locally, but I had trouble with dependencies; the `pyproject.toml` file doesn't list any dependencies, but the tests rely on e.g. `numpy`. Sorry if this is a stupid question; I'm pretty new to this!

**Comment by arogozhnikov** [comment]
Hi @elenishor 

There is no such instruction, just deleted the broken link.

Setting up env for development consists of 1. creating venv. 2. cloning repo. 3. running `python test.py` in repo root
