### ISSUE TITLE
unfold and fold operations

### ISSUE THREAD

**Issue by parthe** [arogozhnikov/einops#234]
It appears `einops` does not support unfold and fold operations which is needed to get overlapping patches.

For cases where window-size equals stride, one can use `einops.rearrange`. But I couldn't find the right way to do this operation when they are unequal.

I am looking for an equivalent to the `torch.nn.functional.unfold` or `torch.Tensor.unfold` operation which works as follows

```python

import torch
n, c, W, H = 100, 3, 32, 21
x = torch.randn(n, c, W, H)

window_x, window_y = 5, 3
stride_x, stride_y = 2, 1
y = x.unfold(2, window_x, stride_x).unfold(3, window_y, stride_y) 
print(y.shape)
# (100, 3, 14, 19, 5, 3)
# (n, c, (W-window_x)/stride_x+1, (H-window_y)/stride_y+1, window_x, window_y)
```

In torch these are `views` whereby the overlapping patches share the same memory

**Comment by arogozhnikov** [comment]
Hi @parthe, 
einops doesn't provide such operations: it is impossible to implement efficient extraction of overlapping patches with correct backprop using only high-level interfaces (e.g. strides manipulations will break backprop). This means backends have to provide this operation as ready.
+ see concerns about reversibility https://github.com/arogozhnikov/einops/issues/34#issuecomment-503410016
