### ISSUE TITLE
Error when using Pytorch==1.9.1, propose change from torch.concat to torch.cat

### ISSUE THREAD

**Issue by jmoso13** [arogozhnikov/einops#237]
https://github.com/arogozhnikov/einops/blob/05a86433d5be1a86ffc3c5a61a9e256360cb2e0a/einops/_backends.py#L307

I'm using an older version of PyTorch and according to their documentation `torch.concat` is just a newer alias for still supported `torch.cat`, I'm getting an error `AttributeError: module 'torch' has no attribute 'concat'` , was wondering if this line above could just be changed to `torch.cat` safely? Thank you!

**Comment by arogozhnikov** [comment]
good point, changed to torch.cat, try version that is currently in master

**Comment by jmoso13** [comment]
works great, thank you!
