### ISSUE TITLE
[Feature suggestion] a simple way to enable concatenation in rearrange

### ISSUE THREAD

**Issue by jdavidls** [arogozhnikov/einops#247]
It is quite common to find cases where it is necessary to concatenate tensors in artificial neural network models. An example could be the concatenation of features coming from different graphs. In this proposal I show a simple trick that, together with the implementation of some validation rules, can be a first approach to enable concatenation as a feature of rearrangement.

I have prepared an example using pytorch:

```python
def _detect_varying_dim(first: pt.Tensor, *more: pt.Tensor) -> Optional[int]:
    '''
    First we need to detect what dim differs in the shape on input tensors
    (only when not all shapes are equal)
    '''
    variying_dim = None
    for dim in range(len(first.shape)):
        if all(other.shape[dim] == first.shape[dim] for other in more):
            continue
        assert variying_dim == None, \
            f'only one dimension can vary in the input tensors, '\
            f'the shape of the input tensors vary in dim {variying_dim} and dim {dim}'
        variying_dim = dim
    return variying_dim
```
```python
def unbind_all(tensors: list[pt.Tensor], /, dim: int):
    '''
    This method may not be very efficient, but it allows us to maintain 
    consistency with the current pattern syntax.
    '''
    # may be this step can be implemented via slices to avoid copy 
    return [ u.unsqueeze(dim) for t in tensors for u in t.unbind(dim=dim) ]    
```

```python
def cat_powered_rearrange(
    tensors: List[pt.Tensor],
    pattern: str,
    /,
    **axes_lengths: dict[str,int]
):
    # If one (and only one) dimension differs in the shape of the incoming tensors, 
    # ... we can do concat :)
    if (dim := _detect_varying_dim(*tensors)) is not None:

        # We only need to unbind all slices in all tensors in that dimension
        tensors = unbind_all(tensors, dim=dim)

    return rearrange(tensors, pattern, **axes_lengths)
```

```python
a = pt.zeros(2,3,5),
b = pt.ones(2,4,5),

cat_powered_rearrange([a, b], 'a b c d ->  b d (a c)')

# torch.Size([2, 5, 7])
```

> Internally, rearrange should do some validations to maintain consistency. 
> In particular, the concatenation could only be performed when the first index is combined with the index of the variying dimension. 
> In the example, this happens when `a` is combined with `c` in ` -> b d (a c)`. 
> 

I am sure that a much more efficient implementation can be done from the guts of einops, in this case I make a simple proposal that could be implemented with a simple wrapper.

I thank you for your good work
#20

**Comment by arogozhnikov** [comment]
Hi @jdavidls 

Thanks for ideas and example code. This has downsides, main ones:

- no reversibility (which is naturally expected from rearrange op) 
- restriction on ordering that is not obvious
- necessity to know sizes of all tensors (rarely used these days, but einops works with symbolic tensors too) 
- additional checks for every operation that will break caching

Just use `einops.pack`, it completely covers concatenation scenario. Add rearrange on result if necessary.
