### ISSUE TITLE
[BUG] Noisy patches generated when using `einops.rearrange` to split a grayscale brain image of `skimage.data`

### ISSUE THREAD

**Issue by Ishak96** [arogozhnikov/einops#257]
# Issue Description
When utilizing `einops.rearrange` to divide a grayscale brain image obtained from `skimage.data` into patches, it appears that the resulting patches contain a considerable amount of noise. This noise negatively impacts the quality of the patches and hinders further processing or analysis of the image data.

# Steps to Reproduce
1. Import `skimage.data` and obtain a grayscale brain image.
2. Use `einops.rearrange` to split the image into patches.
> Brain image
![brain](https://github.com/arogozhnikov/einops/assets/36072891/20470204-200b-40af-bf70-8e5ae469f488)
```python
from einops import rearrang
import numpy as np
from skimage.data import brain

# Load the image
brain_image = brain()[-1][..., np.newaxis]

# Patchify the image
patche_size = 32
patches = rearrange(brain_image, '(h p1) (w p2) c -> (h w) (p1 p2) c', p1=patche_size, p2=patche_size)

# Plot the patches
for i in range(8):
    for j in range(8):
        plt.subplot(8, 8, i*8+j+1)
        plt.axis("off")
        plt.imshow(patches[i*8+j].reshape(patche_size, patche_size, 1), cmap="gray")
```

## Expected Result
The patches generated by `einops.rearrange` should maintain the integrity of the original grayscale brain image without introducing significant noise.

### Results on RGB image
1. Input image
![padded](https://github.com/arogozhnikov/einops/assets/36072891/d757cc06-0c91-41eb-9c23-5430d3c994c6)

2. Patches
![patches](https://github.com/arogozhnikov/einops/assets/36072891/556b1a99-caf2-446d-b2a5-168c0ca6ecc0)

## Actual Result
The patches produced by `einops.rearrange` exhibit a noticeable amount of noise, making them less suitable for subsequent analysis or processing tasks.
![brain_patches](https://github.com/arogozhnikov/einops/assets/36072891/198cfb71-006e-4de1-9a60-ac1c65adbcf2)

**Comment by arogozhnikov** [comment]
this is not related to einops, problem is with visualization script.

In particular, this line

```        
plt.imshow(patches[i*8+j].reshape(patche_size, patche_size, 1), cmap="gray")
```

auto-scales grayscale image (i.e. each patch in this case). To avoid auto-scaling use vmin/vmax.

**Comment by Ishak96** [comment]
thanks,
I have changed it as follows and it worked:
```python
patche = rearrange(patches[i*8+j], '(p1 p2) c -> p1 p2 c', p1=patche_size, p2=patche_size)
plt.imshow(patche, vmin=0, vmax=brain_image.max(), cmap="gray")
```
