### ISSUE TITLE
[Feature suggestion] All/Any Reduction

### ISSUE THREAD

**Issue by George-Ogden** [arogozhnikov/einops#278]
Einops sparks a lot of interest to introduce new operations that either meet specific requirements or look like a plausible extension of existing ones.

Einops is not a purely experimental thing, it's already used in a number of large projects, so there are high expectations for any introduced improvement. Let's see which are they and how to check them?

1. Try to collect **use-cases**
2. **Implementation**. (optional) Implementing a sketch of your proposal in a code allows detecting possible conflicts and realize possible caveats.
3. **Integrity** - does it interplay well with existing operations and notation in einops?
4. **Readability**. This is harder to check, but give it a try. A simple but usable test is to write an exercise sheet with several examples of your extension explained, for others meaning of operation should be guessed. Send this test to a couple of your friends to collect the feedback and see how your notion will be understood. This should also help to improve your ideas to make them more digestible.

Sometimes, I write code that looks like this:
```
valid = mask.any(-1).all(-1)
```
which is pretty confusing.

However, I cannot write
```
valid = einops.reduce(
    einops.reduce(
        mask,
        "b x y -> b x",
        "any"
    ),
    "b x -> b",
    "all"
)
```
I think that having a reduce `all` or a reduce `any` would be a very valuable feature. Currently, this could be done using:
```
valid = einops.reduce(
    einops.reduce(
        mask,
        "b x y -> b x",
        "max"
    ),
    "b x -> b",
    "min"
)
```
but this is not as clean/more likely to produce bugs/less explicit.  
I don't know how hard the implementation would be but I'd like to hear if other people think it would be a feature worth adding.

**Comment by arogozhnikov** [comment]
I certainly see value in any/all for readability.

Got this implemented in master, you can already use it with 

```bash
pip install git+https://github.com/arogozhnikov/einops.git
```

**Comment by George-Ogden** [comment]
Awesome, thanks :pray:
