### ISSUE TITLE
*** AttributeError: 'Rearrange' object has no attribute 'recipe'[BUG]

### ISSUE THREAD

**Issue by yibingchen2023** [arogozhnikov/einops#290]
**Describe the bug**
When I run the code as below:

self.rearrange = Rearrange(equation, **kwargs)
recipe = einops.einops._reconstruct_from_shape_uncached(
         self.rearrange.recipe(), input_size_
  )

An error occurred: " *** AttributeError: 'Rearrange' object has no attribute 'recipe'"

**Reproduction steps**

equation is a string, which is "b (h d) (g0 p0) (g1 p1) (g2 p2) -> (b h) (g0 g1 g2) d (p0 p1 p2)".
input_size_ is a tuple, i.e., (0, 32, 128, 128, 128)
Run  the below codes, the error will be occurred once more:

self.rearrange = Rearrange(equation, **kwargs)
recipe = einops.einops._reconstruct_from_shape_uncached(
         self.rearrange.recipe(), input_size_
  )

**Expected behavior**
First, How can I get the parameter of self.rearrange.recipe()?
Second, I find that _reconstruct_from_shape_uncached() has three parameters, i.e.,  self: TransformRecipe, shape: List[int], axes_dims: FakeHashableAxesLengths. How should I set those three parameters? 
Third, I hope the return value of _reconstruct_from_shape_uncached() is (axes_lengths, output_size). Is it as I guess or expect?

**Your platform**
Version of my einops is 0.7.0, and DL package is pytorch.

**Comment by arogozhnikov** [comment]
There is no case when you need to use `reconstruct_from_shape_uncached`. Example usage:

```python
# in __init__, sizes are examples
self.rearrange = Rearrange("b (h d) (g0 p0) (g1 p1) (g2 p2) -> (b h) (g0 g1 g2) d (p0 p1 p2)", d=2, p0=3, p1=4, p2=5)

# later in forward
tensor_rearranged = self.rearrange(tensor)
```
