### ISSUE TITLE
[BUG] error when import einops

### ISSUE THREAD

**Issue by Adolfhill** [arogozhnikov/einops#293]
**Describe the bug**
there is an error when i try to impoer einops
![image](https://github.com/arogozhnikov/einops/assets/52448551/fd27a212-68dd-48bb-bcf8-babba6c4a006)

**Reproduction steps**
use conda and this file(environment.yml) create env:

name: immatch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2
  - python=3.7
  - pytorch==1.7.0
  - torchvision
  - jupyter
  - scipy
  - matplotlib
  - opencv==4.5.2
  - einops
  - cython
  - kornia

then
conda activate immatch
python
import einops

**Expected behavior**
just import correctly

**Your platform**
Ubuntu22 and python env in above-mentioned file

**Comment by arogozhnikov** [comment]
Hi @Adolfhill 

current einops works with python3.8+ (3.7 reached EOL).
Previous versions, e.g. einops 0.6.x support python 3.7.
