### ISSUE TITLE
[Feature suggestion] Allow performing a view instead of a reshape

### ISSUE THREAD

**Issue by samsja** [arogozhnikov/einops#296]
# Context

First thank you for maintaining this great software.

I would like to be able to call rearrange on a tensor and be sure that it will not copy any data (just change the stride) and if the operation is impossible to raise an error. Currently the behavior is to try do not copy but copy if it is impossible. I would like to have a bit more granularity here. 

To speak in pytorch term I want to be able to perform a `view` operation instead of a `reshape`. 

Implementation wise, it seems that it would actually be quite easy, I would just need to add in the backend a view operation like the reshape [one](https://github.com/arogozhnikov/einops/blob/a6e93530ec2dce44f473e6065fad4d8236cda4f3/einops/_backends.py#L439).

In term of interface it could either be

### 1 - rearrange_view
```python
from einops import rearrange_view
rearrange_view(images, 'b h w c -> b h w c')
```

### 2 - view as a param
```python
from einops import rearrange
rearrange(images, 'b h w c -> b h w c', view=True)
```

## Downside

only Pytorch does support view. Numpy and jax does not support view, only reshape.

So if this feature is too pytorch specific I can understand that it is too specific. Wdyt ?

## Alternative

If I could change the backend on the fly I could create a new backend that call view instead of reshape.

Unfortunately right now there is a direct mapping between tensor type and backend and I cannot change the backend myself.

Second feature request, beeing able to pass a different backend in any einops operation

example

```python
from einops import rearrange
from einops._backend import TorchBackend

class TorchViewBackend(TorchBackend):
        def reshape(self, x, shape):
             return x.view(shape)


rearrange(images, 'b h w c -> b h w c', backend=TorchViewBackend)
```

 Thanks in advance :pray: 

(happy to open a PR if needed)

**Comment by arogozhnikov** [comment]
Hi @samsja ,

you make wrong assumptions about how torch works and subsequently how einops works.

-  when it is possible to return a view, einops returns a view

```python
from einops import rearrange
import torch
x = torch.zeros([2, 3, 4, 5])
y = rearrange(x, 'b h w c -> b c h w')

x.data_ptr() == y.data_ptr()  # outputs True
```

- einops allocates space for result only if that's unavoidable, because result can't be represented as a view to the input

```python
y = rearrange(x, 'b h w c -> b (c h) w')
x.data_ptr() == y.data_ptr() # outputs False
```

should there be a need for `rearrange_view`, here is the optimal implementation:
```python
def rearrange_view(x, pattern):
    result = rearrange(x, pattern)
    assert x.data_ptr() == result.data_ptr(), "result can't be a view to the input"
    return result
```

But from practitioner's perspective it is not helpful - if output can't be a view to the input, you still want to compute it.

**Comment by samsja** [comment]
Thanks for your response.

> when it is possible to return a view, einops returns a view
> einops allocates space for result only if that's unavoidable, because result can't be represented as a view to the input

Yes I am completely aware of this two points. I totally understand that **rearrange will not copy memory if it don't have to** (this is as well pytorch reshape behavior). Yet there is still a difference of utility between view and reshape. View will throw an error if it cannot do without copying memory while reshape will silently create a new tensor. 

> But from practitioner's perspective it is not helpful - if output can't be a view to the input, you still want to compute it.

This is arguable. In my case I specifically want this granularity and be totally sure that I am not copying anything.

I end up implementing something similar to your implementation. I guess that is fine for my use case, tho not totally optimal since you still create a new tensor, whereas view will fail **before** creating it. If I were working with really big tensor I could end with  OOM even if I catch the assert error. Whereas torch.view no copy would have be done if I catch the view error.

Anyway, wdyt of allowing custom backend ? I can totally understand that such `rearrange_view` is not in einops philosophy, tho it would be nice to our own thing with the backend !

Thanks in advance

**Comment by arogozhnikov** [comment]
Ok, cool.

> Anyway, wdyt of allowing custom backend?

too much hassle to pass backend each time. Don't see this as a common use-case, so this won't be a part of package

There are a number of places to achieve this behavior should you _really_ need it:

- If you don't like existing backend - you can monkey-patch it.
- you can just copy-paste function in `my_backend_einops` and replace backend resolution with backend you like: https://github.com/arogozhnikov/einops/blob/master/einops/einops.py#L515

> I end up implementing something similar to your implementation. 

Great, I think this is the most reasonable approach.

closing this as you have a working solution
