### ISSUE TITLE
[Tensorflow] Simple rearrange does not work when dimensions are partially unknown

### ISSUE THREAD

**Issue by LukasDrude** [arogozhnikov/einops#30]
When all axes are known, it works nicely:

```python
import tensorflow as tf
from einops import rearrange

x = tf.placeholder(tf.float32, shape=(2, 5))
print(x.shape)
y = rearrange(x, 'a b -> b a')
print(y.shape)
```
yields:
```
(2, 5)
(5, 2)
```

If some axis are not known (e.g. variable batch size, variable sequence length, ...), reshape does not copy the shape information:

```
import tensorflow as tf
from einops import rearrange

x = tf.placeholder(tf.float32, shape=(None, 5))
print(x.shape)
y = rearrange(x, 'a b -> b a')
print(y.shape)
```
yields
```
(?, 5)
(?, ?)
```

**Comment by arogozhnikov** [comment]
I believe that patch #32 resolves this. Please reopen an issue if I am wrong. Shape derivation is far form perfect, but should work in such simple cases
