### ISSUE TITLE
Add support for keras3

### ISSUE THREAD

**Issue by chicham** [arogozhnikov/einops#300]
Hi there,

the keras team released a new version of keras which do not rely anymore on tensorflow. 

The current implementation of Rearrange, Reduce and EinMix for keras are aliases for tensorflow.

I think it would be a nice addition to einops to add support for keras3. I can submit a pr if you think it is interesting enough.

Best,
Hicham

**Comment by arogozhnikov** [comment]
I've recently implemented array api support in einops, so...

I would recommend starting from implementing [array api](https://data-apis.org/array-api/2022.12/) for keras tensors.
That's not einops-specific, but provides all the benefits: any tensor that implements array api is supported by einops (and scikit-learn, and eindex).

**Comment by chicham** [comment]
Thanks for your feedback, I close the issue then
