### ISSUE TITLE
What am I doing wrong with repeat command?

### ISSUE THREAD

**Issue by asusdisciple** [arogozhnikov/einops#312]
So I have a batch of images(grayscale) which I want to imitate as 3 channel images, because my model expects them.
I found the tutorial and examples however when I try to apply them I always get varying, unexpected results.

So my image Batch has the shape `[B, C, H, W] - 128x1x224x224` from a torch dataloader/dataset.
I thought easy, I can change the 1 to a 3 with einops by doing:

`repeat(images, "b c h w -> b repeat(c) h w", repeat=3)`

But this returns `128x3x1x224x224`, which I do not really understand, the 1 should not be there anymore, since my target vector has a length of 4? I though about using reduce afterwards to get rid of the 1 dimension, but since there are some functions involved (max...) I was not sure if this alters the result.

Can you help me?

**Comment by arogozhnikov** [comment]
```python
repeat(images, 'b 1 h w -> b c h w', c=3)
```

https://stackoverflow.com/ is a better place to ask questions
