### ISSUE TITLE
[BUG] SyntaxError in Python 3.11

### ISSUE THREAD

**Issue by befelix** [arogozhnikov/einops#317]
`einops==0.7.0` has a syntax error in the `einops.py::einsum` docstring, which will lead to a `SyntaxError` when testing code that relies on `einops` with `pytest` in Python >=  3.11. 

This has already been fixed in [this commit](https://github.com/arogozhnikov/einops/commit/db815ca3a1f4d128b6948b7f911288bb2196add6) on the main branch, but there has been no release since. Would it be possible to cut a new minor release that includes the fix?

It might also be of interest to enable [ruff rule `W605`](https://docs.astral.sh/ruff/rules/invalid-escape-sequence/), which auto-fixes these type of issues.

**Comment by arogozhnikov** [comment]
hey @befelix,

- I've just pushed 0.8.0 to pypi
- I've included W rules in ruff, thanks for pointing

**Comment by befelix** [comment]
Thanks a lot @arogozhnikov
