### ISSUE TITLE
im2col and col2im support? 

### ISSUE THREAD

**Issue by IsCoelacanth** [arogozhnikov/einops#34]
way to split images into patches like im2col and col2im where they're inverse operations of each other. Unlike PyTorch which does summation.

eg:
```python
x = torch.rand(1, 3, 64, 64)
y = im2col(x, kernerl_size=5, stride=1)
z = col2im(y, kernel_size=5, stride=1)
```
and x == z.

**Comment by arogozhnikov** [comment]
Einops.rearrange works only with strictly reversible patterns, but in2col and col2im are not this case.
Though when they are reversible (stride = window, so patches don't overlap), you can do that:

```python
x = torch.rand(1, 3, 64, 64) 
y = rearrange(x, 'b c (h h2) (w w2) -> b (c h2 w2) (h w)', h2=4, w2=4)
z = rearrange(y, ' b (c h2 w2) (h w) -> b c (h h2) (w w2)', h2=4, w2=4, h=16)
assert torch.allclose(x, z)
```

**Comment by IsCoelacanth** [comment]
that seems to solve what I was looking for. Thanks!
