### ISSUE TITLE
Combine rearrange and repeat?

### ISSUE THREAD

**Issue by bjourne** [arogozhnikov/einops#344]
I asked ChatGPT about it and it said:

![combine_repeat](https://github.com/user-attachments/assets/dc3d8838-8a58-4701-85b0-eac26edc9635)

I think it would be cool if it worked. :)

**Comment by arogozhnikov** [comment]
wrong prompt - wrong answer

Function exists since 2018.
https://github.com/arogozhnikov/einops/blob/main/docs/1-einops-basics.ipynb
