### ISSUE TITLE
[Feature suggestion] Diag / trace-like reductions

### ISSUE THREAD

**Issue by lukemarris** [arogozhnikov/einops#347]
Numpy's `np.einsum` can implement a number of diagonal reductions by repeating indices. For example:

```
diag = np.einsum("ii->i", matrix)  # np.diag(matrix)
diag = np.einsum("iii->i", tensor) 
trace = np.einsum("ii->", matrix)  # np.trace(matrix) / np.sum(np.diag(matrix))
```

For those not familiar, an exception is raised if any of the repeated dimensions have different size.

I was surprised that `einops.reduce` and `einops.rearrange` does not handle this case. For example all of these fail:

```
diag = einops.rearrange(matrix, "ii->i")
diag = einops.rearrange(tensor, "iii->i") 
matrix = einops.rearrange(diag, "i->ii")
trace = einops.reduce(matrix, "ii->i", "sum")
max_over_diag = einops.reduce(matrix, "ii->i", "max")
```

Dealing with diagonals of matrices/tensors is common when there are symmetries/equivariances in tensors.

Adding this as a feature will also help einops become feature complete with `np.einsum`.

**Comment by arogozhnikov** [comment]
Hi Luke,

> I was surprised that einops.reduce and einops.rearrange does not handle this case. 

```
einops.reduce('b c h w -> b c') averages over h w
einsum('b c n n -> b c') averages over trace. 
```
If reduce supported this logic, a ton of code out there would be incorrect (because - yes - in many cases you want to name same-size dims with same label). So it's simply not allowed.

> Adding this as a feature will also help einops become feature complete with np.einsum.

there is einops.einsum, and this is one of reasons for its existence.

**Comment by lukemarris** [comment]
> If reduce supported this logic, a ton of code out there would be incorrect (because - yes - in many cases you want to name same-size dims with same label). So it's simply not allowed.

For future readers, I was under the impression duplicate entries always raised an exception so it would be safe to add this feature. However I was mistaken. It seems duplicate entries are permitted with the `allow_duplicates` argument. So Alex is right that this feature would break backwards compatibility. 

```
if not (allow_underscore and x == "_") and not allow_duplicates:
    raise EinopsError('Indexing expression contains duplicate dimension "{}"'.format(x))
```
From: https://github.com/arogozhnikov/einops/blob/1d3f9c48047ba147211c8f15a079db8e87766a0b/einops/parsing.py#L53
