### ISSUE TITLE
[BUG] Inplace operation after repeat for tensors on cuda

### ISSUE THREAD

**Issue by ryancll** [arogozhnikov/einops#350]
**Describe the bug**
For tensors generated by repeat func, some inplace operation should not be supported due to shared memory location. While, I found such errors are ignored for tensor on cuda and give wrong results.

**Reproduction steps**
operation for tensor generated by repeat func on cpu:
![image](https://github.com/user-attachments/assets/d0896978-ce51-42af-9c98-dcdfed522b1c)

same operation for tensor generated by repeat on cuda:
![image](https://github.com/user-attachments/assets/f783ffd7-1d9e-44c9-9460-09a7c0bcfdbb)

Apprantly, the result on cuda is wrong.

**Expected behavior**
Allocate new memory for repeated part may solve this problem, or just raise error.

**Your platform**
OS: Ubuntu 22.04
GPU: Nvidia H100
python: 3.10.4
cuda: 11.8
torch: 2.4.1+cu118
einops: 0.8.0

**Comment by arogozhnikov** [comment]
Hi @ryancll 

That's how it is supposed to work, see https://github.com/arogozhnikov/einops/issues/346#issuecomment-2451557394

Cuda behavior is expected - that's how torch always worked, it is interesting that on CPU torch blocks writing multiple values to same position, but cuda doesn't - but that's not up to einops, this inconsistency should be reported to pytorch. 

If you need a fully materialized tensor, use .clone() as error message suggests.
