### ISSUE TITLE
[BUG] einops.layers.torch.Rearrange throws opset error when used in a model made for torch.onnx.export

### ISSUE THREAD

**Issue by ionymikler** [arogozhnikov/einops#355]
**Describe the bug**
Wanting to onnx-export a model that has in its layers some einops' `Rearrange`. A toy example I prepared that replicates the error when I am trying to export it as such:
```python
import torch
from einops.layers.torch import Rearrange
from typing import Tuple

import torch.nn as nn

def pair(t: int) -> Tuple[int, int]:
    return t, t


class PatchEmbeddingSimple(nn.Module):
    def __init__(self, *, image_size: int, patch_size: int, embed_depth: int, pool: str, channels: int):
        super().__init__()
        self.name = "PatchEmbedding"
        
        image_height, image_width = pair(image_size)
        patch_height, patch_width = pair(patch_size)
        patch_dim = channels * patch_height * patch_width

        self.rearrange = Rearrange(
                "b c (h p1) (w p2) -> b (h w) (p1 p2 c)",
                p1=patch_height,
                p2=patch_width,
            )
        self.patch_embedding_linear = nn.Linear(patch_dim, embed_depth)

        self.seq = nn.Sequential(
            self.rearrange,
            self.patch_embedding_linear
        )
    
    def forward(self, image_batch: torch.Tensor):
        out = self.seq(image_batch)
        return out

def export_model(model: nn.Module, _x, onnx_filepath: str):
    print(f"Exporting model '{model.name}' to ONNX format")

    model = torch.jit.script(model)
    torch.onnx.export(
        model=model,
        args=_x,
        f=onnx_filepath,
        verbose=True,
        opset_version=20,
        dynamo=False
        )

    print(f"✅ Model exported to '{onnx_filepath}'")

    return onnx_filepath

def main():
    model_config = {
            "channels_num": 3,
            "image_size": 256,
            "pool": "cls",
            "embed_depth": 1024,
            "patch_size": 32,
        }
    model = PatchEmbeddingSimple(
            image_size=model_config["image_size"],
            patch_size=model_config["patch_size"],
            embed_depth=model_config["embed_depth"],
            pool=model_config["pool"],
            channels=model_config["channels_num"],
    )
    x = torch.randn((2, model_config["channels_num"], model_config["image_size"], model_config["image_size"]))
    onnx_filepath = f"./models/onnx/{model.name}.onnx"
    export_model(model=model, _x=x, onnx_filepath=onnx_filepath)

if __name__ == "__main__":
    main()
```

I get the following error:
```
Traceback (most recent call last):
  File "/home/iony/DTU/f24/thesis/code/early_exit_vit/einops_bug_report.py", line 73, in <module>
    main()
  File "/home/iony/DTU/f24/thesis/code/early_exit_vit/einops_bug_report.py", line 70, in main
    export_model(model=model, _x=x, onnx_filepath=onnx_filepath)
  File "/home/iony/DTU/f24/thesis/code/early_exit_vit/einops_bug_report.py", line 40, in export_model
    torch.onnx.export(
  File "/home/iony/miniconda3/envs/lgvit/lib/python3.9/site-packages/torch/onnx/__init__.py", line 375, in export
    export(
  File "/home/iony/miniconda3/envs/lgvit/lib/python3.9/site-packages/torch/onnx/utils.py", line 501, in export
    _export(
  File "/home/iony/miniconda3/envs/lgvit/lib/python3.9/site-packages/torch/onnx/utils.py", line 1563, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/iony/miniconda3/envs/lgvit/lib/python3.9/site-packages/torch/onnx/utils.py", line 1116, in _model_to_graph
    graph = _optimize_graph(
  File "/home/iony/miniconda3/envs/lgvit/lib/python3.9/site-packages/torch/onnx/utils.py", line 638, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/iony/miniconda3/envs/lgvit/lib/python3.9/site-packages/torch/onnx/utils.py", line 1835, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/home/iony/miniconda3/envs/lgvit/lib/python3.9/site-packages/torch/onnx/symbolic_opset9.py", line 6417, in prim_loop
    torch._C._jit_pass_onnx_block(
RuntimeError: symbolic for __getitem__ produced an incorrect number of outputs (expected 2, but got 1)
```

I did try to export it using the [torch_dynamo backend](https://pytorch.org/docs/stable/onnx_dynamo.html#torch.onnx.dynamo_export), BUT, it does not help me because I am aiming to use control-flow statements and these are not supported for a stable version of pytorch (nightly and 2.6 ought to do so).

Am I missing something?

**Reproduction steps**
On an environment with similar characteristics as the ones described in the '**Environment**' section, take the code into a `main.py` file and simply run:
```bash
python main.py
```
**Expected behavior**
What you expected to happen.

**Your platform**
**Environment**
Name: einops Version: 0.8.0

PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python platform: Linux-5.15.0-127-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.4.131

**Comment by arogozhnikov** [comment]
Hi @ionymikler 

- tested your example and I can confirm it fails
- deleting this line: `model = torch.jit.script(model)` results in successful export. So layer can be exported, and can be scripted - why scripted layer can't be exported is a question for torch team, I don't see anything special on einops side and traceback doesn't help either

**Comment by ionymikler** [comment]
Hi @arogozhnikov
Thank you for looking into it. I don't know enough about how the internal process of the onnx.export works to even try and guess.

Passing to the exporter just the model is not good for me, because I am modeling a network whose inference structure is not invariant. Because of this I  need to capture this dynamics and `torch.jit.script` offered that alternative.

**just as a curiosity **, because of this need of dynamic behavior I had to upgrade to the nightly build of pytorch (2.6.0.dev20241226+cu124) which export just fine w/out scripting. There are  this '[HigherOrder_ops](https://pytorch.org/docs/stable/cond.html#)' that offer this dynamic capture as well without the need for previous scripting
