### ISSUE TITLE
Add `must_return_view` argument to `rearrange`

### ISSUE THREAD

**Issue by philip-bl** [arogozhnikov/einops#38]
I am using pytorch. Suppose I want to `rearrange` a tensor and change some of its elements inplace. But I don't know if `rearrange` will create a view or not. So I think there must either be an argument which means "raise an error iff this rearrange can't be performed using view" or there must be an easy way to determine if my rearrange will create a view or not.

**Comment by arogozhnikov** [comment]
I expect pytorch backend to create a view always when it is possible. Do you observe example when it is not so?

**Comment by philip-bl** [comment]
@arogozhnikov I don't know when it does, I don't know what `rearrange` does under the hood. If it always returns a view, you should write that in the documentation. Also, you could add
`assert returned_tensor.data_ptr() == input_tensor.data_ptr()` in the end of pytorch version of `rearrange`.

**Comment by function2-llx** [comment]
@arogozhnikov 
I can provide an example that pytorch does not create a view.
```python
import torch
from einops import rearrange

x = torch.randn(4, 1, 256, 256, 128)
y = rearrange(x, 'n c (h ph) (w pw) (d pd) -> n h w d (ph pw pd c)', ph=4, pw=4, pd=2)
assert x.data_ptr() == y.data_ptr()
```
I got `AssertionError` on my machine. Maybe pytorch won't create view when the tensor is too large?

**Comment by arogozhnikov** [comment]
Hi @function2-llx ,
yes, that's expected. 

rearrange follows semantics of `torch.reshape` for when creating a new tensor: when result can't be represented as a view to the original tensor (that's what I mean in the previous message).

Your example doesn't permit representing result as a view, and that's not about size of tensor, it is parts that you expect to be aligned: "ph pw pd c" are actually scattered in the original tensor. Completing such operation demands creating a new tensor (as einops does).
