### ISSUE TITLE
pytorch named tensors <> einops integration

### ISSUE THREAD

**Issue by daniel-j-h** [arogozhnikov/einops#39]
I just read through the pytorch 1.3 release notes and found their named tensor feature

https://pytorch.org/docs/stable/named_tensor.html

it looks similar to einops but quite limited and not as powerful - will continue to use einops :grimacing: :rocket: 

I was wondering how einops integration with the named tensor feature could look like; e.g. in

```python
>>> imgs = torch.randn(1, 2, 2, 3 , names=('N', 'C', 'H', 'W'))
>>> imgs.names
('N', 'C', 'H', 'W')

>>> rearrange(imgs, "() c h w -> c h w")
```

should einops check that the names of the input tensors are matching the pattern? What else can be done here?

I understand the named tensors are an experimental feature right now; this ticket is more about starting a discussion from the einops point of view. Thanks! :bow:

**Comment by arogozhnikov** [comment]
Hello Daniel, 

thanks for bringing this up. I had similar thoughts when reading pytorch documentation of named tensors. 

Simplest thing to try is:
- check non-decomposed features on the input, fail when axis name does not coincide with one in einops
- set result's axes names when result axis is not a composed axis

Examples:

```python
rearrange(x, 'b (c1 c2) h w -> b c1 h w') # second axis name will not be checked, will fail if for any other axis name was set, but did not coincide
rearrange(x, 'b (c1 c2) h w -> h w c1 c2 b') # result names are exactly h, w, c1, c2, and b
rearrange(x, 'b (c1 c2) h w -> h (c1 c2) w b ()') # result names are exactly h, None, w, b and None
```

We can try to add this as an experimental module like `einops.named_pytorch` with separate versions of rearrange, reduce and layers.

**Comment by arogozhnikov** [comment]
I think this repo may be of interest as an experiment of interaction einops <-> xarray (xarray names axes), 
https://github.com/arviz-devs/xarray-einstats

I don't have plans to integrate with pytorch's named_tensor; projects related to einops <-> named tensors are welcome in discussions.
