### ISSUE TITLE
[FR] Optional channels

### ISSUE THREAD

**Issue by ehknight** [arogozhnikov/einops#49]
Sometimes, I find myself working lists of tensors in which one tensor has a shape `(b, c)` (for `c` classes) and another tensor has shape `(b,)` (for a single class). My current approach is to pad the tensors that have only one class with an additional channel dimension, use `rearrange` on the list, and then squeeze the dimensions that need to be squeezed.

A great alternative to this would be supporting optional channels. Perhaps you could notate them with a question mark: `rearrange(x, "b c? -> (b c?)")`.

**Comment by arogozhnikov** [comment]
@ehknight thanks for coming up with suggestion.

I've been previously considering this feature, however it is quite difficult to generalize beyond a single optional dimension.
The way your example should be implemented in existing `einops` syntax is:
```
rearrange(x, "b ... -> (b ...)")
```
where ellipsis can be 0 or 1 dimensions (or more). However, right now that's not yet supported and is subject of #43

**Comment by arogozhnikov** [comment]
@ehknight that's implemented now and will become a part of the next release

**Comment by shoyer** [comment]
It looks like transformations like `"b ... -> (b ...)"` work currently, but not `"(b ...) -> b ..."`?

**Comment by arogozhnikov** [comment]
@shoyer that's right, those expressions are disallowed. 

Let's analyze your example:
```python
(b ...) 
```
left part implies there is one dimension which should be composed in `b` and undefined number of dimensions. 
To make this a valid operation one needs to provide number of dimensions in `...` and their sizes. 
In this scenario user can write `...` as separate axes like `(b b1 b2) -> b b1 b2`.

**Comment by arogozhnikov** [comment]
Ellipsis collapsing is now available as a part of einops 0.3 release.
