### ISSUE TITLE
Integration with opt_einsum

### ISSUE THREAD

**Issue by munael** [arogozhnikov/einops#51]
opt_einsum: https://optimized-einsum.readthedocs.io/en/latest/

Not sure how integration would look like.

Maybe with a module flag for "einsum optimizer" (`EINSUM_OPT in ['opt_einsum', None]`). Since the einsum part should work the same for all backends it supports, but the rest of the operations need to be specified per-backend.

Just opening it for discussion :)

**Comment by arogozhnikov** [comment]
Leaving integration of `opt_einsum` to backends. Unlike einops, they can integrate implementation in C or other low-level language and have access to all dimensions in runtime.
