### ISSUE TITLE
Capsules network

### ISSUE THREAD

**Issue by michaelklachko** [arogozhnikov/einops#53]
@arogozhnikov if you like einsum you will love capsules networks: https://github.com/michaelklachko/CapsNet/blob/master/capsnet_cifar.py#L68-L91 someone should do that in pytorch.

**Comment by arogozhnikov** [comment]
@michaelklachko  
it is a good example for using einsum, probably worth adding to a collection of 'writing better code'

**Comment by arogozhnikov** [comment]
@michaelklachko done:

https://github.com/arogozhnikov/readable_capsnet
Capsule networks in 75 lines (for encoder/decoder + separate stackable layer for routing).

Now challenge for you is to rewrite this into tensorflow code!

**Comment by michaelklachko** [comment]
Neat! TF seems to be going out of fashion, when I have time I might try to it in Jax: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.einsum.html

**Comment by arogozhnikov** [comment]
Rewriting in Jax is also a good idea
