### ISSUE TITLE
New pypi release (repeat not part of version installed by pip)

### ISSUE THREAD

**Issue by Froskekongen** [arogozhnikov/einops#55]
Is it possible to get out a new release of einops on pypi?

It seems like the version installable by pip doesn't include `repeat` (which is a very useful op).

**Comment by arogozhnikov** [comment]
sure will do soon, need some time for polishing / documenting

**Comment by lucidrains** [comment]
aw, i was looking forward to using this

**Comment by arogozhnikov** [comment]
@lucidrains in the meanwhile you can just use master branch

```
pip install https://github.com/arogozhnikov/einops/archive/master.zip
```

**Comment by arogozhnikov** [comment]
Einops 0.3 is released and includes `repeat`, so just `pip install einops` will work
