### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by arogozhnikov** [arogozhnikov/einops#65]
- move away from notebooks? 
- Create a documentation webpage?
- have a separate version of second tutorial for each package

**Comment by cgarciae** [comment]
#75 could probably address this?

**Comment by cgarciae** [comment]
It might be a good idea to set

https://arogozhnikov.github.io/einops/

as the project's website or reference it in the readme.

**Comment by arogozhnikov** [comment]
@cgarciae 
yup, just fixed some code in docstrings so that doctests passed with it and added link to a website and a badge.

Thanks a lot!
