### ISSUE TITLE
Requirements Text

### ISSUE THREAD

**Issue by bhishanpdl** [arogozhnikov/einops#67]
Can we use this library only for numpy operations when we do not have tensorflow/torch/etc?
I was looking for the `requirements.txt` file and it was missing in the Github repo.

It would be helpful for starters if there is info about library requirements.

**Comment by arogozhnikov** [comment]
Thanks for asking, `einops` itself is written in a pure python and has no mandatory dependencies.
In other words - you can install only numpy and einops will work. Or you can install any subset of frameworks - and einops will work with all of them.

I'll add a line to project readme

**Comment by bhishanpdl** [comment]
Thanks for the response. This addresses my question. I am closing the issue.
