### ISSUE TITLE
Add nbviewer links for notebooks.

### ISSUE THREAD

**Issue by bhishanpdl** [arogozhnikov/einops#68]
Sometimes when the internet is slow, GitHub takes a long time to open jupyter notebooks, and sometimes it fails to open it.

I would suggest adding `nbviewer links` for `docs/xxx.ipynb` files which open fast and also seem more pleasant (IMO).

**Comment by arogozhnikov** [comment]
Added readme to `/docs` folder with links to nbviewer and html,  have a look

**Comment by bhishanpdl** [comment]
That's great. The issue is now closed.
