### ISSUE TITLE
Idea for chaining expressions

### ISSUE THREAD

**Issue by MilesCranmer** [arogozhnikov/einops#83]
This is admittedly a bit of a crazy idea that I think could be interesting to explore. Interested to hear anybody's thoughts on this.

Basically, I think it would be even more readable and concise if one could chain together multiple operations in a single string. Would also eliminate intermediate variables and multiple einops calls.

Let me explain with an example:

```python
out = einops.chain("""
x1=x: b h w c -> b h w; mean
x2=y: b h w c -> b h w; mean
x1, x2: b h1 w, b h2 w -> b h1 h2
""", x=x, y=y)
```

So, here `x` and `y` are set by keyword args, which would let you pass any number of variables into the chain of expressions. You could potentially run an entire pipeline through a single `einops` chain.

The syntax: `x1=x:` stores the output of the following computation in the "register" `x1`. That would be passed to the next calculations (shown on line 3 of the string). And similar for `x2`.

The syntax: `; mean` would tell `einops` that a reduction operation using mean operation should be performed.

The syntax `x1, x2:` would take the arrays in the temporary variables `x1` and `x2`, and execute the following command using einsum. Since there's no `=`, it just means to output it as the result of the chain. 

If the keyword arg is an integer rather than array, it would be interpreted as a size, e.g.:

```python
einops.chain("ims: (b1 b2) h w c -> h (b1 b2 w) c", ims=ims, b1=2)
```

would do the normal rearrange operation with `b1` set to 2.

Excluding einsum, which is discussed in #73, I don't this would require additional operations. It would just be string parsing and meta-programming of other operations.

This would also be a unified way of doing the other operations, as well as einsum.

Curious to hear opinions on this! And any other syntax ideas for doing this.
Cheers,
Miles

**Comment by Bit0r** [comment]
This is equivalent to an advanced version of einsum?

**Comment by arogozhnikov** [comment]
Hey @MilesCranmer 

I think it would be nice if you criticized your own design from far past :)

(but if you think that's something to chase, have a look at tagstr PEP)

**Comment by MilesCranmer** [comment]
Tag strings look cool!

My thinking has evolved from this issue so I’ll close it.
