### ISSUE TITLE
flipping axis

### ISSUE THREAD

**Issue by CDitzel** [arogozhnikov/einops#85]
is it possible by means of einops to flip input akin to np.flipur or np.fliplr?

**Comment by arogozhnikov** [comment]
Hi @CDitzel,

Currently there is no such operation. You can use common slicing notion to complete flipping:
```python
x[::-1]
and 
x[:, ::-1]
```
This will work the same way in any framework.

Such operations may eventually appear in `einops` as a larger part for indexing operations, but it is not even in the roadmap as of now

**Comment by Maykeye** [comment]
>This will work the same way in any framework.

Torch doesn't support [negative slicing](https://github.com/pytorch/pytorch/issues/59786).  Which makes that to manipulate images code still has to use  `torch.flip`  and similar

**Comment by arogozhnikov** [comment]
@Maykeye see https://github.com/arogozhnikov/einops/discussions/203
