### ISSUE TITLE
Decomposing tensor dimension into multiple dimensions

### ISSUE THREAD

**Issue by CDitzel** [arogozhnikov/einops#86]
How can I achieve this?

I want to transform t from a 5 dimensional tensor into a 7 dimensional tensor, but this
```
        t = rearrange(
            t, "b h p l (q k v) -> b h p l q k v", q=1, k=1, v=1
        )
```

does not work, since 1x1x1 does not equal the 3 of the bracket term on the left hand side

**Comment by arogozhnikov** [comment]
Hi @CDitzel , 

It's not possible, as you pointed out q * k * v = 1 * 1 * 1, but original dimension is of length 3, not 1. 
Note `(q k v)` is not enumeration of components,  it is axis decomposition (so number of elements in original axis should be a product of dimensions).

I believe you want to dissect tensor into 3 tensors, not decompose axis. Right code is:
```
q, k, v = rearrange(t, "b h p l qkv -> qkv b h p l", qkv=3)
```

(each of tensors q, k, v has the same shape `b h p l` now)
