### ISSUE TITLE
Problem Accessing ipynb

### ISSUE THREAD

**Issue by akhilalexander** [arogozhnikov/einops#9]
can't access the einops fundamentals ipynb

**Comment by arogozhnikov** [comment]
@akhilalexander problem still persists? Github sometimes fails to render notebooks

**Comment by akhilalexander** [comment]
yes!

**Comment by arogozhnikov** [comment]
Strange, since it works for me. Try this link in nbviewer:

http://nbviewer.jupyter.org/github/arogozhnikov/einops/blob/master/docs/1-einops-basics.ipynb
