### ISSUE TITLE
Question: How to do repeat interleave?

### ISSUE THREAD

**Issue by janvainer** [arogozhnikov/einops#92]
Hi, I was wondering if `repeat` can also be used for repeating givene elements given number of times along given dimension, similar to `torch.repeat_interleave`. Say I have a sequence `[0,1,2,3]` and repeats specified as `[1,3,2,4]`. The result should be `[0,1,1,1,2,2,3,3,3,3]`. Is this possible with einops? Regards.

**Comment by arogozhnikov** [comment]
There is no such functionality in `einops` right now. 

If you don't find torch syntax appropriate, you can split operations into generation of lookup, and indexing if you don't want to use `repeat_interleave`, you can split that into generation of lookup and indexing


```python
repeats = torch.arange(3, 5)

picked_indices = torch.repeat_interleave(repeats)
x[:, :, picked_indices, :] # for repeats over the third axis
```

It reduces repeat to a usual indexing (what torch does under the hood anyway).
However cases when this gives some considerable boost in readability are extremely rare.

**Comment by janvainer** [comment]
alright, thank you.
