### ISSUE TITLE
Feature Request: Support Jax 

### ISSUE THREAD

**Issue by rwbfd** [arogozhnikov/einops#93]
Is it possible to add some request for Jax? Now it has become more and more inconvenient to do Jax dimension change and reduce etc. 

Thank you very much in advance.

**Comment by shoyer** [comment]
Einops already supports JAX, and it works pretty well in my experience!

Is there some reason (maybe missing documentation?) that explains why this wasn't clear to you?

**Comment by rwbfd** [comment]
@shoyer OK! Thanks is so good to hear! I have only concern that does it work well inside JIT functions?

**Comment by shoyer** [comment]
Einops works great inside JIT. We are using it for performance sensitive
code.

**Comment by rwbfd** [comment]
@shoyer That is so great to hear! Thank you for the awesome work! I will close the issue now.
