### ISSUE TITLE
Is traversal among elements possible?

### ISSUE THREAD

**Issue by ayberkydn** [arogozhnikov/einops#98]
For example, is zigzag traversal pattern possible with einops? It would be great if there were a generic operation that could be flexible enough to implement complicated traversal patterns like this. 

Just an idea, if there could be an object what it should do when in a scalar element in any tensor. Later, a traversal pattern that emerges could be stored in memory at the first run and could be parallelized using this order afterwards.

**Comment by arogozhnikov** [comment]
Hi @ayberkydn, numerous traversal patterns can be implemented in einops for tensors of arbitrary dimensionality IF those have blocky structure. Basically, any rearrange operation with 1-dimensional output implements a traversal.

For patterns that don't fall in this category (including zigzag), use [standard indexing with a tuple of indexing arrays](https://numpy.org/doc/stable/user/basics.indexing.html#indexing-multi-dimensional-arrays).
