### ISSUE TITLE
cuTENSOR GPU Backend

### ISSUE THREAD

**Issue by mnicely** [arogozhnikov/einops#99]
Hi @arogozhnikov, 
I wanted to reach out and see if you'd be integrated in using [cuTENSOR](https://developer.nvidia.com/cutensor) as another direct GPU backend...

+ Vis @springer13 @v0i0

**Comment by arogozhnikov** [comment]
Hi @mnicely, thanks for dropping a suggestion. 

Recently got to this, there is a considerable overlap in functionality between cuTensor and einops, but cuTensor is kind of a very different backend to integrate into einops. 

I don't think anyone uses tensors without some kind of nicer wrapper (like ones provided by frameworks), while einops is more of application-level targeted. The right direction is to get cuTensor integrated directly into frameworks which einops relies on. 

I see cuTensor has some integration into cupy already, would be nice to see more.
